#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#

PeerOrgs:
  - Name: Org2
    Domain: org2.example.com
    # EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
